# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Madlab'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: HCL AppScan Enterprise@2
  inputs:
    ServiceEndPointAse: 'ASE_Parimal_Test_JOY'
    jobName: 'afas'
    folderId: 11
    templateId: 11
    testPolicyId: abcd
    applicationId: 11
    description: 'kf'
    contact: 'kfgj'
    startingURL: 'demotestfilre'
    loginMethod: 'None'

